#11 feat : 페이지네이션 & 알람 기능 1차 완성
AJD-Archive/Kkeujeok_Frontend pull request #66
Opened 2024-09-19 05:34 UTC by sinamong0620

## 🪄 목적

> 관련 이슈 : #11

<br />
<br />

## 💻 상세 작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요.

- 자기소개 수정시 되는 페이지네이션과 친구 초대를 했을때 뜨는 실시간 알람을 구현했어요
- 추후에 페이지네이션을 모달로 변경하고 실시간 알람 또한 ... 으로 보이게 다시 수정할거에요

<br />
<br />

## 📸 스크린샷

<br />
<br />

## 👼🏻 리뷰 요구사항 (선택)

> 리뷰어가 특별히 봐줬으면 하는 부분이 있다면 작성해주세요.

2024-09-19 05:38 UTC, MyungJiwoo requested changes

2024-09-19 05:38 UTC, MyungJiwoo commented on src/pages/MainPage.tsx
> +  useEffect(() => {}, []);
이 코드는 어떤 코드인가요?

2024-09-19 08:17 UTC, sinamong0620 commented on src/pages/MainPage.tsx
> +  useEffect(() => {}, []);
엥 무언가의 작업을 하려다가만 것 같습니다... 지울게요..!

2024-09-22 10:09 UTC, MyungJiwoo approved these changes

2024-09-22 10:09 UTC, MyungJiwoo commented on src/styles/MyPageStyled.tsx
> +  background: white;
프로젝트 세팅때 설정해주신 테마로 활용해주시면 나중에 유지보수할 때 더 좋을 것 같습니다~!

2024-09-22 10:22 UTC, sinamong0620 commented on src/styles/MyPageStyled.tsx
> +  background: white;
죄송해요.. 이렇게 안하려고 했는데 아무리 봐도 이 방법 밖에 없어서 그랫습니다 ㅠㅠㅠ..

2024-09-22 10:22 UTC, merged